### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by sapphicsophia** [Elite-Modding-Team/MoCreaturesExtended#157]
`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-06-06 21:55:20 CEST
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.FMLLaunchHandler.isDeobfuscatedEnvironment()Z
    at drzhark.mocreatures.dimension.MoCWorldProviderWyvernSkylands.init(MoCWorldProviderWyvernSkylands.java:37)
    at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
    at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:126)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:750)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 6.5.0-35-generic
  Java Version: 1.8.0_402, Private Build
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
  Memory: 2942900200 bytes (2806 MB) / 6393692160 bytes (6097 MB) up to 6561988608 bytes (6258 MB)
  JVM Flags: 2 total; -Xms409m -Xmx7040m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2739 181 mods loaded, 180 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State   | ID                                | Version                  | Source                                             | Signature                                |
       |:------- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | UCHIJAA | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
       | UCHIJAA | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
       | UCHIJAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2739-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAA | forge                             | 14.23.4.2739             | forge-1.12.2-14.23.4.2739-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAA | openmodscore                      | 0.11.5                   | minecraft.jar                                      | None                                     |
       | UCHIJAA | foamfixcore                       | 7.7.4                    | minecraft.jar                                      | None                                     |
       | UCHIJAA | obfuscate                         | 0.2.4                    | minecraft.jar                                      | None                                     |
       | UCHIJAA | srm-hooks                         | 1.12.2-1.0.0             | minecraft.jar                                      | None                                     |
       | UCHIJAA | movillages                        | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                         | None                                     |
       | UCHIJAA | actuallyadditions                 | 1.12.2-r137              | ActuallyAdditions-1.12.2-r137.jar                  | None                                     |
       | UCHIJAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | UCHIJAA | actuallybaubles                   | 1.1                      | ActuallyBaubles-1.12-1.1.jar                       | None                                     |
       | UCHIJAA | infinitylib                       | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                             | None                                     |
       | UCHIJAA | agricraft                         | 2.12.0-1.12.0-a5         | agricraft-2.12.0-1.12.0-a5.jar                     | None                                     |
       | UCHIJAA | applecore                         | 3.1.3                    | AppleCore-mc1.12.2-3.1.3.jar                       | None                                     |
       | UCHIJAA | crafttweaker                      | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
       | UCHIJAA | mtlib                             | 3.0.5                    | MTLib-3.0.5.jar                                    | None                                     |
       | UCHIJAA | modtweaker                        | 4.0.13                   | modtweaker-4.0.13.jar                              | None                                     |
       | UCHIJAA | jei                               | 4.11.0.204               | jei_1.12.2-4.11.0.204.jar                          | None                                     |
       | UCHIJAA | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | UCHIJAA | appliedenergistics2               | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar              | None                                     |
       | UCHIJAA | mdecore                           | 1.12-1.0                 | mdecore-1.12-1.0.jar                               | None                                     |
       | UCHIJAA | autooredictconv                   | 1.12-1.0                 | autooredictconv-1.12-1.0.jar                       | None                                     |
       | UCHIJAA | psi                               | r1.1-59                  | Psi-r1.1-59.jar                                    | None                                     |
       | UCHIJAA | quark                             | r1.4-125                 | Quark-r1.4-125.jar                                 | None                                     |
       | UCHIJAA | autoreglib                        | 1.3-18                   | AutoRegLib-1.3-18.jar                              | None                                     |
       | UCHIJAA | bno                               | 1.12.2-1.0.0.0           | BasicNetherOres-1.12.2-1.0.1.0.jar                 | None                                     |
       | UCHIJAA | betteradvancements                | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar             | None                                     |
       | UCHIJAA | betterbuilderswands               | 0.12.0                   | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar    | None                                     |
       | UCHIJAA | bettervillagers                   | 1.12.2-0.2.0.0           | BetterVillagers-1.12.2-0.2.0.0.jar                 | None                                     |
       | UCHIJAA | biomesoplenty                     | 7.0.1.2394               | BiomesOPlenty-1.12.2-7.0.1.2394-universal.jar      | None                                     |
       | UCHIJAA | bloodmoon                         | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAA | bookshelf                         | 2.3.552                  | Bookshelf-1.12.2-2.3.552.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAA | botania                           | r1.10-354                | Botania r1.10-354.jar                              | None                                     |
       | UCHIJAA | codechickenlib                    | 3.2.0.345                | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAA | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAA | brandonscore                      | 2.4.3                    | BrandonsCore-1.12.2-2.4.3.168-universal.jar        | None                                     |
       | UCHIJAA | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | UCHIJAA | chancecubes                       | 1.12.2-3.2.1.224         | ChanceCubes-1.12.2-3.2.1.224.jar                   | None                                     |
       | UCHIJAA | chesttransporter                  | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | UCHIJAA | ctm                               | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                          | None                                     |
       | UCHIJAA | chisel                            | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                       | None                                     |
       | UCHIJAA | chunkpregenerator                 | 4.4.0                    | Chunk-Pregenerator-1.12.2-4.4.5.jar                | None                                     |
       | UCHIJAA | cofhcore                          | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar             | None                                     |
       | UCHIJAA | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAA | cyclopscore                       | 0.11.8                   | CyclopsCore-1.12.2-0.11.8.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCHIJAA | colossalchests                    | 1.6.11                   | ColossalChests-1.12.2-1.6.11.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCHIJAA | commoncapabilities                | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar                  | None                                     |
       | UCHIJAA | controlling                       | 3.0.6                    | Controlling-3.0.6.jar                              | None                                     |
       | UCHIJAA | cookingforblockheads              | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
       | UCHIJAA | extendedrenderer                  | v1.0                     | coroutil-1.12.1-1.2.11.jar                         | None                                     |
       | UCHIJAA | coroutil                          | 1.12.1-1.2.11            | coroutil-1.12.1-1.2.11.jar                         | None                                     |
       | UCHIJAA | configmod                         | v1.0                     | coroutil-1.12.1-1.2.11.jar                         | None                                     |
       | UCHIJAA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
       | UCHIJAA | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
       | UCHIJAA | cucumber                          | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                          | None                                     |
       | UCHIJAA | cxlibrary                         | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
       | UCHIJAA | ptrmodellib                       | 1.0.2                    | PTRLib-1.0.2.jar                                   | None                                     |
       | UCHIJAA | props                             | 2.6.0                    | Decocraft-2.6.0_1.12.2.jar                         | None                                     |
       | UCHIJAA | disenchanter                      | 1.6                      | disenchanter-[1.12]1.6.jar                         | None                                     |
       | UCHIJAA | thermalfoundation                 | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAA | draconicevolution                 | 2.3.12                   | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar | None                                     |
       | UCHIJAA | thermalexpansion                  | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAA | mocreatures                       | 12.4.3                   | DrZharks-MoCreatures-Extended-12.4.3.jar           | None                                     |
       | UCHIJAA | elevatorid                        | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                       | None                                     |
       | UCHIJAA | csb_ench_table                    | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                     | None                                     |
       | UCHIJAA | endercore                         | 1.12.2-0.5.35            | EnderCore-1.12.2-0.5.35.jar                        | None                                     |
       | UCHIJAA | enderio                           | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderiointegrationtic             | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderiobase                       | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderioconduits                   | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderioconduitsappliedenergistics | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | refinedstorage                    | 1.6                      | refinedstorage-1.6.jar                             | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | UCHIJAA | enderioconduitsopencomputers      | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderioconduitsrefinedstorage     | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                           | None                                     |
       | UCHIJAA | natura                            | 1.12.2-4.3.2.49          | natura-1.12.2-4.3.2.49.jar                         | None                                     |
       | UCHIJAA | forestry                          | 5.8.1.325                | forestry_1.12.2-5.8.1.325.jar                      | None                                     |
       | UCHIJAA | enderiointegrationforestry        | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | tinkersextras                     | 1.12.2-1.0.5             | TinkersExtras-1.12.2-1.0.5.jar                     | None                                     |
       | UCHIJAA | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
       | UCHIJAA | enderiointegrationticlate         | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | ichunutil                         | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
       | UCHIJAA | nei                               | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAA | ftblib                            | 5.2.0.25                 | FTBLib-5.2.0.25.jar                                | None                                     |
       | UCHIJAA | enderiomachines                   | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderiopowertools                 | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAA | enderstorage                      | 2.4.4.132                | EnderStorage-1.12.2-2.4.4.132-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.8.1.jar                         | None                                     |
       | UCHIJAA | zerocore                          | 1.12-0.1.2.2             | zerocore-1.12-0.1.2.2.jar                          | None                                     |
       | UCHIJAA | bigreactors                       | 1.12.2-0.4.5.49          | ExtremeReactors-1.12.2-0.4.5.49.jar                | None                                     |
       | UCHIJAA | foamfix                           | 0.9.9.1-1.12.2           | foamfix-0.9.9.1-1.12.2-anarchy.jar                 | None                                     |
       | UCHIJAA | forgelin                          | 1.7.4                    | Forgelin-1.7.4.jar                                 | None                                     |
       | UCHIJAA | forgemultipartcbe                 | 2.4.2.60                 | ForgeMultipart-1.12.2-2.4.2.60-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAA | microblockcbe                     | 2.4.2.60                 | ForgeMultipart-1.12.2-2.4.2.60-universal.jar       | None                                     |
       | UCHIJAA | minecraftmultipartcbe             | 2.4.2.60                 | ForgeMultipart-1.12.2-2.4.2.60-universal.jar       | None                                     |
       | UCHIJAA | fortuneores                       | v0.3                     | FortuneOres v0.3 1.12.2.jar                        | None                                     |
       | UCHIJAA | fpsreducer                        | 1.12.2-1.10.2            | FpsReducer-1.12.2-1.10.2.jar                       | None                                     |
       | UCHIJAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                        | None                                     |
       | UCHIJAA | ftbutilities                      | 5.2.0.30                 | FTBUtilities-5.2.0.30.jar                          | None                                     |
       | UCHIJAA | cfm                               | 5.3.0                    | furniture-5.3.0-1.12.2.jar                         | None                                     |
       | UCHIJAA | gamestages                        | 2.0.91                   | GameStages-1.12.2-2.0.91.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAA | gravestone                        | 1.10.1                   | gravestone-1.10.1.jar                              | None                                     |
       | UCHIJAA | gravitygun                        | 7.0.0                    | GravityGun-1.12.2-7.0.1.jar                        | None                                     |
       | UCHIJAA | harvest                           | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                          | None                                     |
       | UCHIJAA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | UCHIJAA | inventorypets                     | 1.5.2                    | inventorypets-1.12-1.5.2.jar                       | None                                     |
       | UCHIJAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAA | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
       | UCHIJAA | ironchest                         | 1.12.2-7.0.44.829        | ironchest-1.12.2-7.0.44.829.jar                    | None                                     |
       | UCHIJAA | magicclover                       | 1.12-0.7.8               | magicclover-1.12-0.7.8.jar                         | None                                     |
       | UCHIJAA | malisiscore                       | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
       | UCHIJAA | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | UCHIJAA | radixcore                         | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
       | UCHIJAA | mca                               | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                     | None                                     |
       | UCHIJAA | mcjtylib_ng                       | 3.0.3                    | mcjtylib-1.12-3.0.3.jar                            | None                                     |
       | UCHIJAA | mekanism                          | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
       | UCHIJAA | mekanismtools                     | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
       | UCHIJAA | projecte                          | 1.12-PE1.3.1B            | ProjectE-1.12-PE1.3.1B.jar                         | None                                     |
       | UCHIJAA | moartinkers                       | 0.6.0                    | moartinkers-0.6.0.jar                              | None                                     |
       | UCHIJAA | mob_grinding_utils                | 0.3.8                    | MobGrindingUtils-0.3.8.jar                         | None                                     |
       | UCHIJAA | modnametooltip                    | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                   | None                                     |
       | UCHIJAA | morefurnaces                      | 1.10.5                   | MoreFurnaces-1.12.2-1.10.5.jar                     | None                                     |
       | UCHIJAA | moreoverlays                      | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                     | None                                     |
       | UCHIJAA | morpheus                          | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                            | None                                     |
       | UCHIJAA | mousetweaks                       | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                       | None                                     |
       | UCHIJAA | mrtjpcore                         | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar            | None                                     |
       | UCHIJAA | gachashroom                       | 1.0.0                    | MushroomQuest 1.12.2 - v1.7.jar                    | None                                     |
       | UCHIJAA | mysticalagriculture               | 1.6.12                   | mysticalagriculture-1.12-1.6.12.jar                | None                                     |
       | UCHIJAA | naturescompass                    | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
       | UCHIJAA | neat                              | 1.4-16                   | Neat 1.4-16.jar                                    | None                                     |
       | UCHIJAA | netherfoundation                  | 1.2.0                    | NetherFoundation-1.12.2-1.2.0-universal.jar        | None                                     |
       | UCHIJAA | netherportalfix                   | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar                  | None                                     |
       | UCHIJAA | omlib                             | 3.0.0-148                | omlib-1.12.2-3.0.0-148.jar                         | None                                     |
       | UCHIJAA | openmods                          | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAA | openblocks                        | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAA | openglider                        | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
       | UCHIJAA | openmodularturrets                | 3.0.1-257                | openmodularturrets-1.12.2-3.0.1-257.jar            | None                                     |
       | UCHIJAA | oreexcavation                     | 1.4.119                  | OreExcavation-1.4.119.jar                          | None                                     |
       | UCHIJAA | p455w0rdslib                      | 2.0.29                   | p455w0rdslib-1.12-2.0.29.jar                       | None                                     |
       | UCHIJAA | harvestcraft                      | 1.12.2u                  | Pam's HarvestCraft 1.12.2u.jar                     | None                                     |
       | UCHIJAA | projectred-core                   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                | None                                     |
       | UCHIJAA | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                  | None                                     |
       | UCHIJAA | randomthings                      | 4.1.9                    | RandomThings-MC1.12.2-4.1.9.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAA | redstonearsenal                   | 2.5.1                    | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAA | refinedstorageaddons              | 0.4                      | refinedstorageaddons-0.4.jar                       | None                                     |
       | UCHIJAA | xreliquary                        | 1.12.2-1.3.4.767         | Reliquary-1.12.2-1.3.4.767.jar                     | None                                     |
       | UCHIJAA | respawnablepets                   | 1.0.6                    | respawnable-pets-1.0.6.1.jar                       | None                                     |
       | UCHIJAA | rftools                           | 7.55                     | rftools-1.12-7.55.jar                              | None                                     |
       | UCHIJAA | secretroomsmod                    | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                    | None                                     |
       | UCHIJAA | simplyjetpacks                    | 2.2.7.45                 | SimplyJetpacks2-1.12.2-2.2.7.45.jar                | None                                     |
       | UCHIJAA | somanyenchantments                | 0.3.0                    | SoManyEnchantments V0.3.1 (1.12.2).jar             | None                                     |
       | UCHIJAA | stg                               | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
       | UCHIJAA | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                    | None                                     |
       | UCHIJAA | storagedrawersextra               | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar                | None                                     |
       | UCHIJAA | taiga                             | 1.3.2                    | taiga-1.12.2-1.3.2.jar                             | None                                     |
       | UCHIJAA | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAA | texfix                            | 4.0                      | TexFix V-1.12-4.0.jar                              | None                                     |
       | UCHIJAA | tickdynamic                       | 1.0.1                    | TickDynamic-1.12.2-1.0.1.jar                       | fc6c96880539df54ba847abda8844dabfcef307e |
       | UCHIJAA | tinker_io                         | release 2.6.1            | tinker_io-1.12.2-release 2.6.1.jar                 | None                                     |
       | UCHIJAA | tinkersaddons                     | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar                   | None                                     |
       | UCHIJAA | tcomplement                       | ${version}               | TinkersComplement-1.12.2-0.2.3b.jar                | None                                     |
       | UCHIJAA | tinkersjei                        | 1.0                      | tinkersjei-1.0.jar                                 | None                                     |
       | UCHIJAA | tinkerstages                      | 2.0.15                   | TinkerStages-1.12.2-2.0.15.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAA | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar                | None                                     |
       | UCHIJAA | torchmaster                       | 1.6.4.62                 | torchmaster_1.12.2-1.6.4.62.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | UCHIJAA | ts2k16                            | 1.2.9                    | TS2K16-1.2.9.jar                                   | None                                     |
       | UCHIJAA | twilightforest                    | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar        | None                                     |
       | UCHIJAA | vanillafix                        | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                            | None                                     |
       | UCHIJAA | vehicle                           | 0.18.0                   | vehicle-mod-0.18.0-1.12.2.jar                      | None                                     |
       | UCHIJAA | veinminer                         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | UCHIJAA | veinminermodsupport               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | UCHIJAA | wailaharvestability               | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
       | UCHIJAA | wawla                             | 2.5.257                  | Wawla-1.12.2-2.5.257.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAA | weather2                          | 1.12.1-2.6.10            | weather2-1.12.1-2.6.10.jar                         | None                                     |
       | UCHIJAA | what                              | 0.2                      | WHAT-0.2.jar                                       | None                                     |
       | UCHIJAA | immersiveengineering              | 0.12-84                  | ImmersiveEngineering-0.12-84.jar                   | None                                     |
       | UCHIJAA | reauth                            | 3.6.0                    | reauth-3.6.0.jar                                   | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | UCHIJAA | solcarrot                         | 1.8.4                    | solcarrot-1.12.2-1.8.4.jar                         | None                                     |
       | UCHIJAA | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
       | UD      | mdecore-core                      | 1.0                      | minecraft.jar                                      | None                                     |
  Loaded coremods (and transformers): AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
                                        openmods.core.OpenModsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (TickDynamic-1.12.2-1.0.1.jar)
                                        com.wildex999.patcher.TransformerPatcher
                                        com.wildex999.patcher.EntityInjector
                                      LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      PregenHooks (Chunk-Pregenerator-1.12.2-4.4.5.jar)
                                        pregenerator.config.impl.internal.CarbonConfigHooks
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Quark-r1.4-125.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      MDECore-Core (mdecore-1.12-1.0.jar)
                                        com.mattdahepic.mdecore.asm.TickrateTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleFeature (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: DrZhark's Mo'Creatures Extended (mocreatures)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by ACGaming** [comment]
> forge-1.12.2-14.23.4.2739-universal.jar

Please update to a recent version of Minecraft Forge and try again!
