### ISSUE TITLE
Unable to carry tamed Pet Creature with Carry On Mod

### ISSUE THREAD

**Issue by Type-32** [Elite-Modding-Team/MoCreaturesExtended#160]
Gives a NullPointerException on the Goat NBT on joining a world after the bug is replicated.

Replication Steps:
1. Create a new world
2. Tame and name a goat
3. carry it
4. Crash
5. Rejoin world
6. Crash on world loading stage

[latest.log](https://github.com/user-attachments/files/15944589/latest.log)

**Comment by ACGaming** [comment]
```
at tschipp.carryon.common.item.ItemEntity.getEntity(ItemEntity.java:188)
at tschipp.carryon.common.item.ItemEntity.func_77663_a(ItemEntity.java:140)
```

Might be related to Carry On.

**Comment by Type-32** [comment]
It's related to Carry On, just managed to replicate the issue on my end.
But it only happens when you try to carry a MoCreature entity that's already turned into a pet.
