### ISSUE TITLE
Missing sound for hurt dragon fly causes server crash

### ISSUE THREAD

**Issue by Hryper** [Elite-Modding-Team/MoCreaturesExtended#81]
Caused by: java.lang.IllegalArgumentException: Key for sound effect SoundEvent{soundName=mocreatures:dragonflyhurtsoundEventId=549} not found?
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[minecraft_server.1.12.2.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftSound.getBySoundEffect(CraftSound.java:568) ~[CraftSound.class:1.12.2-7d6be591]
	at org.bukkit.craftbukkit.v1_12_R1.CraftSound.getSoundByEffect(CraftSound.java:581) ~[CraftSound.class:1.12.2-7d6be591]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.populateFields(CraftEventFactory.java:489) ~[CraftEventFactory.class:1.12.2-7d6be591]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:422) ~[CraftEventFactory.class:1.12.2-7d6be591]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:416) ~[CraftEventFactory.class:1.12.2-7d6be591]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1342) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1152) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:309) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:231) ~[vq.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:483) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2426) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:318) ~[vq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2329) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2283) ~[amu.class:?]
	at net.minecraft.world.World.redirect$zzl000$updateEntity(World.java:4502) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2065) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923) ~[MinecraftServer.class:?]

**Comment by dooblykid** [comment]
This bug also applies to bees, and regular flys.

**Comment by IcarussOne** [comment]
And it looks like another unfortunate oversight, sorry about the mess.
